version: '3'

services:
  app:
    image: node:14.21.3-alpine
    container_name: 'MARPlify_app'
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: >
      sh -c "
        yarn &&
        yarn start
      "
