version: '3'

services:
  app:
    image: node:14.21.3-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - '3000:3000'
    command: >
      sh -c "
        yarn &&
        yarn start
      "
  api:
    image: node:18.18.2-alpine
    working_dir: /api
    volumes:
      - ./api:/api
    ports:
      - '8080:3000'
    command: >
      sh -c "
        yarn build ; yarn &&
        yarn build ; yarn start
      "
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keystone