version: '3'

services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - api
  web:
    image: node:18.18.2-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    command: >
      sh -c "
        yarn &&
        yarn dev --host 0.0.0.0
      "
  api:
    build:
      context: ./api
    volumes:
      - ./api:/go/src/app
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
  tbls:
    image: k1low/tbls
    working_dir: /work
    volumes:
      - ./:/work
    command: doc
    depends_on:
      - db
