version: '3'

services:
  web:
    image: node:18.18.2-alpine
    working_dir: /app
    volumes:
      - ./web:/app
    ports:
      - '3000:5173'
    command: >
      sh -c "
        yarn &&
        yarn dev --host 0.0.0.0
      "
  api:
    build:
      context: ./api
    volumes:
      - ./api:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
