version: '3'

services:
  app:
    image: node:18.18.2-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:5173
    command: >
      sh -c "
        yarn &&
        yarn dev --host 0.0.0.0
      "