---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: marplify
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: marplify-web
        image: yumekiti/marplify-web:01d0b92
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: marplify
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      initContainers:
        - name: init-migration
          image: yumekiti/marplify-api:01d0b92
          command: ["yarn", "keystone", "prisma", "migrate", "dev", "--name", "init"]
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
      containers:
        - name: marplify-api
          image: yumekiti/marplify-api:01d0b92
      containers:
      - name: marplify-api
        image: yumekiti/marplify-api:01d0b92
        ports:
        - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: marplify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: marplify-db
          image: postgres:16.0-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: keystone
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
            - name: db-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-persistent-storage
          persistentVolumeClaim:
            claimName: db-pv-claim
