---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: marplify
spec:
  selector:
    matchLabels:
      app: app
  replicas: 2
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: marplify
          image: yumekiti/marplify:50257a6
          ports:
            - containerPort: 80
