apiVersion: apps/v1
kind: Deployment
metadata:
  name: marplify
  namespace: marplify
spec:
  selector:
    matchLabels:
      app: marplify
  replicas: 2
  template:
    metadata:
      labels:
        app: marplify
    spec:
      containers:
      - name: marplify
        image: yumekiti/marplify:latest
        ports:
        - containerPort: 80
