---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: marplify
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: marplify-web
        image: yumekiti/marplify-web:latest
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: marplify
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: marplify-api
        image: yumekiti/marplify-api:latest
        ports:
        - containerPort: 3000
---