apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: marplify
spec:
  ingressClassName: nginx
  rules:
  - host: marplify.yumekiti.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
  - host: marplify-api.yumekiti.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api
            port:
              number: 3000