---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: marplify
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: marplify
spec:
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort