name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers for app
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get git commit short hash
        id: get-commit
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Build and push Docker image for app
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          file: ./Dockerfile
          platforms: linux/arm64
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          tags: |
            yumekiti/marplify:${{ steps.get-commit.outputs.commit_hash }}
            yumekiti/marplify:latest

      - name: Update deployment.yaml for app
        run: |
          sed -i "s/yumekiti\/marplify:.*/yumekiti\/marplify:${{ steps.get-commit.outputs.commit_hash }}/" .argocd/deployment.yaml

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Commit and push changes to deploy branch
        run: |
          git config --global user.name '${{ secrets.GIT_USERNAME }}'
          git config --global user.email '${{ secrets.GIT_USEREMAIL }}'
          git add .
          git commit --no-verify -m "Update Docker images and ArgoCD versions"
          git push --force origin main
