name: Auto Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Get Docker credentials
      id: docker-login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Cache Docker layers
      uses: actions/cache@v2
      id: cache-docker
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}

    - name: Build and push Docker image
      id: build-and-push-image
      run: |
        directories=("api" "web")

        for directory in "${directories[@]}"; do
          cd $directory
          DOCKER_TAG=$(git rev-parse --short HEAD)
          docker buildx build --tag yumekiti/marplify-$directory:${DOCKER_TAG} --file Dockerfile --platform linux/arm64 --push --cache-from=type=local,src=/tmp/.buildx-cache --cache-to=type=local,dest=/tmp/.buildx-cache
          sed -i "s/yumekiti\/marplify-$directory:.*/yumekiti\/marplify-$directory:${DOCKER_TAG}/" ../.argocd/deployment.yaml
          cd ..
        done

    - name: Commit and push changes to deploy branch
      run: |
        git config --global user.name '${{ secrets.GIT_USERNAME }}'
        git config --global user.email '${{ secrets.GIT_USEREMAIL }}'
        git add .
        git commit --no-verify -m "Update Docker images and ArgoCD versions"
        git push origin deploy
